import React from 'react';
import Head from 'next/head';

import NavBar from '@/components/NavBar';
import Header from '@/components/Header';
import SideBar from '@/components/SideBar';
import Footer from '@/components/Footer';

// import styles from '@/styles/Layout.module.css';

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <Head>
        <title>GlamPronto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <NavBar />
      {/* <main className={styles.container}> */}
      <main>
        <Header />
        <SideBar />
        {children}
        <Footer />
      </main>
    </div>
  );
}
